name: CI

on:
  push:
    branches: [master, try]
  pull_request:
    branches: [master]

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Run commands
        run: |
          python3 -m pip install --upgrade pip virtualenv
          sudo apt update
          python3 ./mach bootstrap
          python3 ./mach build --dev
